using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InternTrackAI.Data.Migrations
{
    /// <inheritdoc />
    public partial class FixPostgreSqlAutoIncrement : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // All app tables were created by SQLite-generated migrations that use
            // .Annotation("Sqlite:Autoincrement", true). On PostgreSQL this annotation
            // is ignored, leaving Id as a plain integer with no sequence — inserts fail
            // with "null value in column Id violates not-null constraint".
            // Fix: add IDENTITY to each Id column and sync the sequence to max(Id).
            if (migrationBuilder.ActiveProvider != "Npgsql.EntityFrameworkCore.PostgreSQL")
                return;

            foreach (var table in new[]
            {
                "JobApplications",
                "UserProfiles",
                "ResumeVersions",
                "CoverLetterVersions",
                "GeneratedCoverLetters",
                "InterviewPrepSessions",
            })
            {
                migrationBuilder.Sql($"""
                    ALTER TABLE "{table}" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
                    SELECT setval(
                        pg_get_serial_sequence('"{table}"', 'Id'),
                        COALESCE(MAX("Id"), 0) + 1,
                        false
                    ) FROM "{table}";
                """);
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider != "Npgsql.EntityFrameworkCore.PostgreSQL")
                return;

            foreach (var table in new[]
            {
                "JobApplications",
                "UserProfiles",
                "ResumeVersions",
                "CoverLetterVersions",
                "GeneratedCoverLetters",
                "InterviewPrepSessions",
            })
            {
                migrationBuilder.Sql($"""ALTER TABLE "{table}" ALTER COLUMN "Id" DROP IDENTITY;""");
            }
        }
    }
}
