using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InternTrackAI.Data.Migrations
{
    /// <summary>
    /// PostgreSQL-only repair for columns that SQLite-scaffolded migrations created with the wrong
    /// store type. EF writes the migration's explicit <c>type: "TEXT"</c> (or the TEXT type recorded
    /// in the migration's target model) verbatim, so on Npgsql these became <c>text</c> columns:
    /// inserts silently coerce the timestamp to a string, and every read throws
    /// <c>InvalidCastException: Reading as 'System.DateTime' is not supported for fields having
    /// DataTypeName 'text'</c>. <c>FixPostgreSqlTypesAndAddDataProtection</c> repaired the columns
    /// that existed at the time; this migration covers the two it could not know about:
    /// <list type="bullet">
    /// <item><c>ApplicationNotes.CreatedAt</c> (table added later, no provider branch).</item>
    /// <item><c>AspNetUsers.LockoutEnd</c> (DateTimeOffset from the Identity scaffold, typed TEXT via the target model).</item>
    /// </list>
    /// It also gives <c>ApplicationNotes.Id</c> the identity that <c>FixPostgreSqlAutoIncrement</c>
    /// added to every older table, since without it note inserts fail with 23502 before the column
    /// type is ever reached. Every statement is idempotent. No-op on SQLite.
    /// </summary>
    public partial class FixApplicationNoteCreatedAtType : Migration
    {
        private const string Npgsql = "Npgsql.EntityFrameworkCore.PostgreSQL";

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider != Npgsql) return;

            // NOT NULL column: blank/whitespace legacy text can't become NULL, so it falls back to now().
            // "::text" first makes the expression valid whether the column is still text or already timestamptz.
            migrationBuilder.Sql("""
                ALTER TABLE "ApplicationNotes"
                    ALTER COLUMN "CreatedAt" TYPE timestamp with time zone
                    USING COALESCE(NULLIF(btrim("CreatedAt"::text), '')::timestamp with time zone, now());
                """);

            // Nullable column: blank text becomes NULL (= not locked out).
            migrationBuilder.Sql("""
                ALTER TABLE "AspNetUsers"
                    ALTER COLUMN "LockoutEnd" TYPE timestamp with time zone
                    USING NULLIF(btrim("LockoutEnd"::text), '')::timestamp with time zone;
                """);

            // Identity for ApplicationNotes.Id, only if it doesn't have one yet.
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_attribute
                        WHERE attrelid = '"ApplicationNotes"'::regclass AND attname = 'Id' AND attidentity <> '')
                    THEN
                        ALTER TABLE "ApplicationNotes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
                        PERFORM setval(pg_get_serial_sequence('"ApplicationNotes"', 'Id'),
                                       COALESCE((SELECT MAX("Id") FROM "ApplicationNotes"), 0) + 1, false);
                    END IF;
                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider != Npgsql) return;

            migrationBuilder.Sql("""ALTER TABLE "ApplicationNotes" ALTER COLUMN "CreatedAt" TYPE text USING "CreatedAt"::text;""");
            migrationBuilder.Sql("""ALTER TABLE "AspNetUsers" ALTER COLUMN "LockoutEnd" TYPE text USING "LockoutEnd"::text;""");
            migrationBuilder.Sql("""ALTER TABLE "ApplicationNotes" ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;""");
        }
    }
}
